### ISSUE TITLE
Convert project to Rails v4.2

### ISSUE THREAD

**Issue by kaivalyagandhi** [uwblueprint/somo#4]

**Comment by dinahshi** [comment]
Fixed by https://github.com/uwblueprint/somo/commit/6cd8f30b77bb1acbcd39579c918ca82284da5967

**Comment by MKhowaja** [comment]
I don't think this was actually fixed. We're running into issues when we try to start the server and they are errors that show up because of downgrading to v4.2

**Comment by dinahshi** [comment]
Ah, I see. Perhaps worth scraping everything and just creating a new Rails project with 4.2. Especially since very little has been coded as of yet.

**Comment by chrisjluc** [comment]
@katrinacrisostomo will be doing this

**Comment by MKhowaja** [comment]
Out of curiosity I'm still not 100% clear as to why we're switching versions. Is it because 5.0 is missing features?

**Comment by chrisjluc** [comment]
It doesn't have any new features that benefits us in any significant way. We feel it's safer to use a version of the framework that is more stable and reliable, especially as we're going to hand this off in the coming months to Somo.

**Comment by dinahshi** [comment]
Fixed by https://github.com/uwblueprint/somo/commit/93f2d8473f043d9e8933088fdc77694af4aadf6f and https://github.com/uwblueprint/somo/pull/22
